const GET_SHOTS_SAGA = 'GET_SHOTS_SAGA';
const GET_SHOT_SAGA = 'GET_SHOT_SAGA';
const SET_SHOTS = 'SET_SHOTS';
const SET_SHOT = 'SET_SHOT';
const CLEAR_STORE = 'CLEAR_STORE';

export {  
  GET_SHOTS_SAGA,
  GET_SHOT_SAGA,
  SET_SHOTS,
  SET_SHOT,
  CLEAR_STORE
};
